DB_HOST = "data-sandbox.c1tykfvfhpit.eu-west-2.rds.amazonaws.com"
DB_PORT = 5432
DB_NAME = "pagila"
DB_USER = ""  # Fill in from noodle
DB_PASSWORD = ""  # Fill in from noodle
DB_OPTIONS = "-c search_path=mystic_manuscript"
